#!/bin/sh
if test $# == 1 && test "$1" == '-h';then
    echo "ff [dir] filename   #find the file "
    exit 0
fi

printf "\e[32m_________________start find $1 $2_________________\e[0m\n"
printf "\e[32m==================================================\e[0m\n"
if test $# == 2 ;then
find $1 -type d -path '*/\.*' -prune -o -not -name '.*' -type f -name "*$2*" -print 2>/dev/null
else
find . -type d -path '*/\.*' -prune -o -not -name '.*' -type f -name "*$1*" -print 2>/dev/null
fi