#!/bin/sh

if test $# == 1 && test "$1" == '-h';then
    echo "fs string [directory]   #find the string in directory"
    exit 0
fi

printf "\e[32mWILL RUN:grep $@ \e[0m\n"
printf "\e[32m==================================================\e[0m\n"

if test $# == 1 ;then
    set -x
    grep -I -s --colour=always --color=always -r -n "$1" *
else
    set -x
    grep -I -s --colour=always --color=always -r -n "$@"
fi



# -I :no bianry file
# -s :silenc file