#!/bin/sh

if test $# == 1 ;then
    if test "$1" == '-h';then
        echo "fs string [directory]   #find the string in directory"
        exit 0
    fi
fi

dir=$(pwd)/*
if test $# == 1 ;then
target="grep -I -s --colour=always --color=always -r -n $@ ${dir}"
else
echo $2
target="grep -I -s --colour=always --color=always -r -n $1 $2/*"
fi
printf "\e[32mWILL RUN:${target}\e[0m\n"
printf "\e[32m==================================================\e[0m\n"
${target}


# -I :no bianry file
# -s :silenc file